CREATE TABLE EmailAuth (
`num`    INT(10)  AUTO_INCREMENT     NOT NULL primary key,
`id`     VARCHAR(20)     NOT NULL,
`encoding_value`     VARCHAR(100)  NOT NULL,
	FOREIGN KEY (id)
	REFERENCES User(id) ON UPDATE CASCADE ON DELETE RESTRICT
);
